### ISSUE TITLE
Comma-Separated Selectors

### ISSUE THREAD

**Issue by cyouh95** [stephanierajabi/prj-rev-bwfs-dasmoto#2]
Alternatively, you could use comma-separated selectors to specify the shared properties among multiple elements:

```css
.brushes, .frames, .paint {
  font-size: 32px;
  font-weight: 700;
  color: white;
}
```

https://github.com/stephanierajabi/prj-rev-bwfs-dasmoto/blob/master/DevProjects/Dasmoto/resources/css/style.css#L17-L36
